[package]
name = "containerd-shim-spin-v2"
version = "0.12.0"
authors = ["SpinKube Engineering Team"]
edition = "2021"
repository = 'https://github.com/spinkube/containerd-shim-spin'
license = "Apache-2.0"
homepage = 'https://github.com/spinkube/containerd-shim-spin'
description = """
Containerd shim for running Spin workloads.
"""

[dependencies]
containerd-shim-wasm = { git = "https://github.com/containerd/runwasi", branch = "debug6" }
containerd-shim = "0.6.0"
log = "0.4"
spin-app = { git = "https://github.com/fermyon/spin", tag = "v2.2.0" }
spin-core = { git = "https://github.com/fermyon/spin", tag = "v2.2.0" }
spin-trigger = { git = "https://github.com/fermyon/spin", tag = "v2.2.0" }
spin-trigger-http = { git = "https://github.com/fermyon/spin", tag = "v2.2.0" }
spin-redis-engine = { git = "https://github.com/fermyon/spin", tag = "v2.2.0" }
trigger-sqs = { git = "https://github.com/fermyon/spin-trigger-sqs", tag = "v0.6.0" }
spin-manifest = { git = "https://github.com/fermyon/spin", tag = "v2.2.0" }
spin-loader = { git = "https://github.com/fermyon/spin", tag = "v2.2.0" }
spin-oci = { git = "https://github.com/fermyon/spin", tag = "v2.2.0" }
spin-common = { git = "https://github.com/fermyon/spin", tag = "v2.2.0" }
wasmtime = "17.0.0"
tokio = { version = "1", features = ["rt"] }
openssl = { version = "*", features = ["vendored"] }
serde = "1.0"
serde_json = "1.0"
url = "2.3"
anyhow = "1.0"
oci-spec = { version = "0.6.3" }
futures = "0.3"
ctrlc = { version = "3.2", features = ["termination"] }

