spin_manifest_version = 2

[application]
name = "spin-multi-trigger-app"
version = "0.1.0"
authors = ["Rajat Jindal <rajatjindal83@gmail.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "spin-http-trigger"

[component.spin-http-trigger]
source = "spin-http-trigger/target/wasm32-wasi/release/spin_http_trigger.wasm"
allowed_outbound_hosts = []
[component.spin-http-trigger.build]
command = "cd spin-http-trigger && cargo build --target wasm32-wasi --release && cd -"
watch = ["src/**/*.rs", "Cargo.toml"]

[application.trigger.redis]
address = "redis://redis-service.default.svc.cluster.local:6379"

[[trigger.redis]]
channel = "testchannel"
component = "spin-redis-trigger"

[component.spin-redis-trigger]
source = "spin-redis-trigger/target/wasm32-wasi/release/spin_redis_trigger.wasm"
allowed_outbound_hosts = ["redis://redis-service.default.svc.cluster.local:6379"]
[component.spin-redis-trigger.build]
command = "cd spin-redis-trigger && cargo build --target wasm32-wasi --release && cd -"