name: ci
on:
  pull_request:
    branches: [main]
env:
  CARGO_TERM_COLOR: always
jobs:

  build-wasm-images:
    uses: ./.github/workflows/docker-build-push.yaml
    with:
      test: true

  test:
    needs: build
    runs-on: ubuntu-latest
    env:
      ARCH: x86_64
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - uses: azure/setup-kubectl@v3
      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler libseccomp-dev
      - name: Extract containerd-shim-spin-linux-${{ env.ARCH }}
        run: |
          mkdir -p ./bin
          wget https://filebin.net/bp7mu6jo9hoo5oih/containerd-shim-spin-v2 -O ./bin/containerd-shim-spin-v2
          echo "92f8c0c568174bf077a3c9d596d28c89bf92a41f0783fb72fbb84ae72d20311b ./bin/containerd-shim-spin-v2" | sha256sum --check --status
      - name: install k3d
        run: make install-k3d
        working-directory: ./deployments/k3d
      - name: run integration tests
        run: BIN_DIR="./bin" make integration-tests
      - name: clean up k3d
        if: always()
        run: make tests/clean
