name: ci
on:
  pull_request:
    branches: [main]
env:
  CARGO_TERM_COLOR: always
jobs:

  build-wasm-images:
    uses: ./.github/workflows/docker-build-push.yaml
    with:
      test: true


  test:
    runs-on: ubuntu-latest
    env:
      ARCH: x86_64
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - uses: azure/setup-kubectl@v3
      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler libseccomp-dev
      - name: Extract containerd-shim-spin-linux-${{ env.ARCH }}
        run: |
          mkdir -p ./bin
          wget https://filebin.net/sjefdmnruokppzf9/containerd-shim-spin-v2 -O ./bin/containerd-shim-spin-v2
          chmod +x ./bin/containerd-shim-spin-v2
          echo "be3f8cf78c82332c189512df288d195a769e99f1738488a4fc6f3fac04dbf6cc ./bin/containerd-shim-spin-v2" | sha256sum --check --status
      - name: install k3d
        run: make install-k3d
        working-directory: ./deployments/k3d
      - name: run integration tests
        run: BIN_DIR="./bin" make integration-tests
      - name: clean up k3d
        if: always()
        run: make tests/clean
